### ISSUE TITLE
Tip: $_SERVER['argv'] ignores well-formed URLs as last argument

### ISSUE THREAD

**Issue by MrPetovan** [asika32764/php-simple-console#3]
See: https://forum.friendi.ca/display/ec054ce7255abe539d63ace362184392

Further test revealed that when a CLI script is called with a fully-formed URL as the last argument, `$_SERVER['argv']` won't pick it up while `$argv` does.

`script.php`
````php
#!/usr/bin/env php
<?php
var_dump($_SERVER['argv']);
var_dump($argv);

````
`$> php script.php test http://example.com`
Output:
```
array (
  0 => 'script.php',
  1 => 'test ',
)
array (
  0 => 'script.php',
  1 => 'test ',
  2 => 'http://example.com'
)
```
The `Console::parseArgv` gets passed `$_SERVER['argv']` by default, so the Console wouldn't pick on on the argument as well. Here's the workaround I used:

````php
#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';

// (new \Asika\SimpleConsole\Console())->execute();
(new \Asika\SimpleConsole\Console($argv))->execute();
````
I'm not sure if and how it can be fixed but for anyone else wondering the workaround might be useful.

**Comment by MrPetovan** [comment]
Related PR: https://github.com/friendica/friendica/pull/4718

**Comment by asika32764** [comment]
This is my test code on MacOS (php 7.1.8)

```php
#!/usr/bin/env php
<?php

print_r($argv);
print_r($_SERVER['argv']);
```

```
php argv.php a b http://github.com/
```

And result is 

![180331-0001](https://user-images.githubusercontent.com/1639206/38159424-14f4820c-34db-11e8-9823-3afc5a8ae156.jpg)

Maybe the problem is from environment? Or I miss something?

**Comment by asika32764** [comment]
Also tested on Linux server

![180331-0002](https://user-images.githubusercontent.com/1639206/38159485-e1210d0a-34db-11e8-8b15-87700dd8f96b.jpg)

**Comment by MrPetovan** [comment]
Ugh, never mind, we are messing up with `$_SERVER['argv']` in Friendica. 🙄

Sorry for the disturbance. I should have actually tested my test code. 😅

The workaround works great though.
